version: '3'
services:
  backend:
    build: ./backend
    container_name: php-backend
    ports:
      - "8000:80"
    volumes:
      - backend-src:/var/www/html
    networks:
      - app-network
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: your_database_name
      DB_USER: your_database_user
      DB_PASSWORD: your_database_password

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend-src:/app/src
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  backend-src:
    driver: local
  frontend-src:
    driver: local
  postgres-data:
    driver: local
