version: '3.8'

services:
  # Frontendの設定
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    networks:
      - app-network

  # Backendの設定
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - postgres  # これを追加

  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  # DBの設定
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: keiba_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend-node-modules:
    driver: local
  postgres-data:
    driver: local
